require("/plugin_config/gitignore")
require("/plugin_config/harpoon")
require("/plugin_config/buffer_manager")
require("/plugin_config/refactoring")
require("/plugin_config/undo_tree")
require("/plugin_config/colorizer")
require('/plugin_config/lsp')
require("/plugin_config/lua_snip")
require("/plugin_config/neodev")
require("/plugin_config/null_ls")
require("/plugin_config/nvim_tree")
require("/plugin_config/telescope")
require("/plugin_config/tree_sitter")
-- require("/plugin_config/indent_blank_line")
require("/plugin_config/nvim-ts-rainbow")

require("/plugin_config/llama")
